### PR TITLE
Tm/random fixes

### LINKED ISSUE #47: Implement PropTypes

### LINKED ISSUE #60: Add routing for incorrect paths

### PR DESCRIPTION
**Pull request by tarynmartin**
#### What’s this PR do?
- Adds prop types to all necessary components
- Adds redirect for bad paths
- Cleans up file structure to be more accurate (JobForm doesn't use Redux, so should be in components, not containers)

#### Where should the reviewer start?
- all the component and container files

#### How should this be manually tested?
- in terminal, run npm start. There should be no prop type errors in the browser console

#### What are the relevant tickets?
resolves #47 resolves #60 

- [x] checked to see it passes all tests

### CODE REVIEW

File: src/containers/App/App.js [hunk 1]
```diff
@@ -119,3 +121,8 @@ function App() {
 }
 
 export default App;
+
+App.propTypes = {
+  allJobs: PropTypes.object,
+  errorMsg: PropTypes.string
+};
```
Comment (NakiNorton) [inline src/containers/App/App.js:128]: Thanks for implementing the PropTypes!

**Review by NakiNorton — APPROVED** [review]
Great to get the PropTypes done!
